/*
 * イベント名、ブース、スタンプ、景品などの差し替えはこのファイルで行えます。
 * QRコードに設定する値は各ブースの qrValue です。
 */
window.MINI_APP_CONFIG = {
  brand: {
    name: "FUJIFILM",
    eventName: "FUJIFILM PHOTO EXPERIENCE 2026",
    shortEventName: "PHOTO EXPERIENCE 2026",
  },

  theme: {
    primary: "#e60012",
    primaryStrong: "#b5000e",
    ink: "#151515",
    muted: "#6d6d6d",
    background: "#f2f2ef",
    surface: "#ffffff",
  },

  welcome: {
    eyebrow: "CAMERA STAMP RALLY",
    title: "カメラと出会う、\n6つのブースをめぐろう。",
    description: "会場内の対象ブースでQRコードを読み取って、かわいいカメラスタンプを集めよう。すべて集めるとイベント限定アイテムをプレゼント！",
    eventDate: "2026.08.22 SAT — 23 SUN",
    venue: "FUJIFILM PHOTO EXPERIENCE 会場",
    startLabel: "スタンプラリーをはじめる",
  },

  rally: {
    totalLabel: "全6ブース",
    progressTitle: "STAMP COLLECTION",
    completeMessage: "すべてのカメラと出会いました！",
    scanButton: "QRコードを読み取る",
    mapTitle: "BOOTH GUIDE",
    mapDescription: "番号順でなくても、好きなブースから回れます。",
  },

  booths: [
    {
      id: "x100vi",
      number: "01",
      zone: "X SERIES",
      name: "X100VI",
      boothName: "PREMIUM COMPACT",
      description: "クラシックなデザインと色表現を体験",
      location: "Aホール・入口右手",
      image: "./assets/camera-x100vi.jpg",
      stampColor: "#f3c7bd",
      accentColor: "#ba5144",
      stampTitle: "まいにちカメラ",
      qrValue: "FUJIFILM-STAMP:x100vi",
    },
    {
      id: "xt5",
      number: "02",
      zone: "X SERIES",
      name: "X-T5",
      boothName: "PHOTO STYLE",
      description: "ダイヤル操作で写真を撮る歓びを体験",
      location: "Aホール・中央",
      image: "./assets/camera-xt5.jpg",
      stampColor: "#f5d98d",
      accentColor: "#8b6509",
      stampTitle: "クラシックカメラ",
      qrValue: "FUJIFILM-STAMP:xt5",
    },
    {
      id: "xm5",
      number: "03",
      zone: "X SERIES",
      name: "X-M5",
      boothName: "VLOG & TRAVEL",
      description: "小さく軽やかなVlog撮影を体験",
      location: "Aホール・奥",
      image: "./assets/camera-xm5.jpg",
      stampColor: "#badfd8",
      accentColor: "#32776d",
      stampTitle: "おでかけカメラ",
      qrValue: "FUJIFILM-STAMP:xm5",
    },
    {
      id: "gfx100sii",
      number: "04",
      zone: "GFX SERIES",
      name: "GFX100S II",
      boothName: "LARGE FORMAT",
      description: "ラージフォーマットの立体感を体験",
      location: "Bホール・入口左手",
      image: "./assets/camera-gfx100sii.jpg",
      stampColor: "#c6c8e7",
      accentColor: "#585b9b",
      stampTitle: "じっくりカメラ",
      qrValue: "FUJIFILM-STAMP:gfx100sii",
    },
    {
      id: "instax-mini-evo",
      number: "05",
      zone: "instax™",
      name: "mini Evo",
      boothName: "PRINT EXPERIENCE",
      description: "撮って選んでプリントする楽しさを体験",
      location: "Bホール・中央",
      image: "./assets/instax-mini-evo.png",
      stampColor: "#b9d5ed",
      accentColor: "#356b96",
      stampTitle: "プリントカメラ",
      qrValue: "FUJIFILM-STAMP:instax-mini-evo",
    },
    {
      id: "instax-wide-evo",
      number: "06",
      zone: "instax™",
      name: "WIDE Evo",
      boothName: "WIDE CREATIVITY",
      description: "ワイドな一枚で自由な表現を体験",
      location: "Bホール・奥",
      image: "./assets/instax-wide-evo.png",
      stampColor: "#dfc5e8",
      accentColor: "#80518f",
      stampTitle: "ワイドカメラ",
      qrValue: "FUJIFILM-STAMP:instax-wide-evo",
    },
  ],

  completion: {
    eyebrow: "ALL STAMPS COMPLETE!",
    title: "コンプリート！",
    description: "6つのブースをめぐって、すべてのカメラスタンプを集めました。",
    instruction: "景品交換カウンターで、スタッフに次の画面を見せてください。",
    buttonLabel: "景品交換画面を表示する",
  },

  reward: {
    eyebrow: "EVENT REWARD",
    title: "イベント限定\nカメラステッカーセット",
    description: "スタンプラリー達成特典",
    counter: "景品交換カウンター",
    staffInstruction: "この画面をスタッフにお見せください",
    caution: "交換操作はスタッフが行います。ご自身では押さないでください。",
    staffButton: "スタッフの方が操作してください",
    confirmTitle: "景品をお渡ししますか？",
    confirmDescription: "交換済みにすると元に戻せません。景品をお渡ししてから操作してください。",
    exchangeButton: "景品をお渡しして交換済みにする",
    exchangedTitle: "交換済み",
    exchangedDescription: "景品のお渡しが完了しました",
  },
};

